# Introduction to Numpy
Learning NumPy!

In [1]:
import numpy as np
np.__version__

'1.14.5'

## Differences between lists and NumPy Arrays
* An array's size is immutable.  You cannot append, insert or remove elements, like you can with a list.
* All of an array's elements must be of the same [data type](https://docs.scipy.org/doc/numpy-1.14.0/user/basics.types.html).
* A NumPy array behaves in a Pythonic fashion.  You can `len(my_array)` just like you would assume.

In [2]:
gpas_as_list = [4.0, 3.286, 3.5]

In [3]:
# Can have elements appended to it
gpas_as_list.append(4.0)
# Can have multiple datatypes in it.
gpas_as_list.insert(1, "Whatevs")
# Can have items removed
gpas_as_list.pop(1)

'Whatevs'

In [4]:
gpas_as_list

[4.0, 3.286, 3.5, 4.0]

In [5]:
gpas = np.array(gpas_as_list)

In [6]:
?gpas

In [7]:
gpas.dtype

dtype('float64')

In [8]:
gpas.itemsize

8

In [9]:
gpas.size

4

In [10]:
len(gpas)

4

In [11]:
gpas.nbytes

32

## Multidimensional Arrays
* The data structure is actually called `ndarray`, representing any **n**umber of **d**imensions
* Arrays can have multiple dimensions, you declare them on creation
* Dimensions help define what each element in the array represents.  A two dimensional array is just an array of arrays
* **Rank** defines how many dimensions an array contains 
* **Shape** defines the length of each of the array's dimensions
* Each dimension is also referred to as an **axis**, and they are zero-indexed. Multiples are called **axes**.
* A 2d array is AKA **matrix**.

In [12]:
students_gpas = np.array([
    [4.0, 3.286, 3.5, 4.0],
    [3.2, 3.8, 4.0, 4.0],
    [3.96, 3.92, 4.0, 4.0]
], np.float16)
students_gpas

array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

In [13]:
students_gpas.ndim

2

In [14]:
students_gpas.shape

(3, 4)

In [15]:
students_gpas.size

12

In [16]:
len(students_gpas)

3

In [17]:
students_gpas.itemsize

2

In [18]:
students_gpas.itemsize * students_gpas.size

24

In [19]:
%whos ndarray

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
students_gpas   ndarray    3x4: 12 elems, type `float16`, 24 bytes


In [20]:
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7ff8309074c0
byteorder:  little
byteswap:  False
type: float16


In [21]:
students_gpas[2]

array([3.96, 3.92, 4.  , 4.  ], dtype=float16)

In [22]:
students_gpas[2][3]

4.0

## About data types
* By choosing the proper [data type](https://docs.scipy.org/doc/numpy-1.14.0/user/basics.types.html) you can greatly reduce the size required to store objects
* Data types are maintained by wrapping values in a [scalar representation](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.scalars.html)
* `np.zeros` is a handy way to create an empty array filled with zeros.

In [23]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [24]:
%whos

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
gpas_as_list    list       n=4
np              module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
students_gpas   ndarray    3x4: 12 elems, type `float16`, 24 bytes
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [25]:
60 * 24

1440

In [26]:
study_minutes[0] = 150

In [27]:
first_day_minutes = study_minutes[0]

In [28]:
first_day_minutes

150

In [29]:
type(first_day_minutes)

numpy.uint16

In [30]:
# TODO: Add 60 minutes to the second day in the study_minutes array
study_minutes[1] = 60

In [32]:
study_minutes[2:6] = [80, 60, 30, 90]

## Creation 
* You can create a random but bound grouping of values using the `np.random` package.  
  * `RandomState` let's you seed your randomness in a way that is repeatable.
* You can append a row in a couple of ways
   * You can use the `np.append` method.  Make sure the new row is the same shape.
   * You can create/reassign a new array by including the existing array as part of the iterable in creation.


## Indexing
* You can use an indexing shortcut by separating dimensions with a comma.  
* You can index using a `list` or `np.array`.  Values will be pulled out at that specific index.  This is known as fancy indexing.
  * Resulting array shape matches the index array layout.  Be careful to distinguish between the tuple shortcut and fancy indexing.

In [33]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])

In [34]:
study_minutes.shape

(2, 100)

In [36]:
# Set round 2 day 1 to 60
study_minutes[1][0] = 60

In [37]:
study_minutes[1, 0]

60

In [38]:
1, 0

(1, 0)

In [39]:
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [40]:
[fake_log[3], fake_log[8]]

[44, 50]

In [41]:
fake_log[[3, 8]]

array([44, 50], dtype=uint16)

In [42]:
index = np.array([
    [3, 8],
    [0, 1]
])
fake_log[index]

array([[ 44,  50],
       [132, 122]], dtype=uint16)

In [44]:
study_minutes = np.append(study_minutes, [fake_log], axis=0)

In [46]:
study_minutes[1, 1] = 360

In [47]:
study_minutes

array([[150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 60, 360,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   